### ISSUE TITLE
[Speed] Will this IUF faster than original sha3?

### ISSUE THREAD

**Issue by nightwalker89** [brainhub/SHA3IUF#6]
[Speed] Is this IUF faster than original sha3?

**Comment by brainhub** [comment]
Please provide specific reference to the code. This project doesn't use the most optimized code for SHA3, favouring simplicity and portability instead. 

Hashing the whole buffer is in theory faster than incrementally hashing its portions with multiple `Update` invocations. However, the overhead may be undetectable, especially in this implementation of SHA3.  

In this project we perform minimal amount of data buffering, buffering only what's absolutely necessary -- up to one block (200 bytes), directly into SHA3 state. To be precise, input is not even stored in any temporary buffer -- it is always added directly into the state.  

In many protocols and applications the entire input buffer is available. In this case simply call `sha3_Update()` once. Otherwise, call `sha3_Update()` as you have input available -- there should be no overhead for this in this implementation.

**Comment by brainhub** [comment]
Closing. I am open to add speed-test to this project. Please request if you need it. 

This wasn't intended as top-performance code, but I do try to write this C code to be both well-optimized and simple.
