### ISSUE TITLE
API normalisation compared to other implementations

### ISSUE THREAD

**Issue by HarryR** [brainhub/SHA3IUF#7]
Hi,

 I'm using your SHA3 implementation, but had to fork and make some changes: https://github.com/HarryR/SHA3IUF - I made some basic limited changes (added CMake support, Windows build, appveyor, travis-ci etc.), and I will work out how to contribute them back after syncing my fork with your repo.

 It was the easiest repo to get working for both SHA3 and Keccak support (which I need for Ethereum compatibility). Really good work :D

 However, I noticed some differences and some missing things while using it, these are:

 * Defines for the digest size, e.g. `MD5_DIGEST_LENGTH`
 * The `_Final` function usually copies the digest into the target buffer, rather than returning a pointer to it
 * There is a utility function, e.g. `MD5()` which specifies the input buffer, input length, and pointer to output location to copy result digest to.

 See header files at:

  * https://boringssl.googlesource.com/boringssl/+/HEAD/include/openssl/sha.h
  * https://boringssl.googlesource.com/boringssl/+/HEAD/include/openssl/poly1305.h
  * https://boringssl.googlesource.com/boringssl/+/HEAD/include/openssl/md5.h
  * https://github.com/ninhnguyennhut/linux-4.9.x/blob/1bd34faf35a7a5797f64584d35414d7e625a5032/include/crypto/sha3.h
  * https://github.com/renlord/evmdb/blob/f0762bab1802f1c8c17a53aa36c600f21d55e1fb/src/sha3/sha3.c
 * https://github.com/mjosaarinen/tiny_sha3/blob/dcbb3192047c2a721f5f851db591871d428036a9/sha3.h

I suggest some changes to the API, to make it a near drop-in replacement for the `libcrypto` implementations:

 * Define for digest size, e.g. `SHA3_224_DIGEST_SIZE`
 * Define for block size, e.g. `SHA3_224_BLOCK_SIZE`
 * `_Final` function compatible with libcrypto, e.g. `int sha3_final(void *md, sha3_ctx_t *c);    // digest goes to md`
 * Variants of `sha3_final` function for each digest size, where the size of the output buffer is specified, e.g. `sha3_256_final(uint8_t md[32], sha3_ctx_t* c);`
 * Individual one-shot functions for each variant, e.g. `uint8_t *MD5(const uint8_t *data, size_t len, uint8_t *out);`

TBH the three things I noticed when using your implementation were:

 * no defines for digest size
 * `_final` function returns rather than copies to a buffer
 * `mmap` not compatible with Windows, had to replace with `fopen` and `fread` etc.

Does this sound reasonable?

**Comment by brainhub** [comment]
Thank you for your feedback, @HarryR  . 

I added a single-buffer operation. I think it's a useful addition. Please review a7e8f56317bde756734581006d12de704c3323f3 .

I will happily take your Windows fixes.

One of my goals is to keep the APIs at the necessary minimum. 

- The output size equals the 'number' used during initialization, in bits E.g. for sha3_Init256, it will be 256 output bits. One small problem here with using enums is that now we will need two sets of macros/enums: one for the input because we want to use bits (256, 384, 512), and one for output, because we want to use bytes there (32, 48, 64). 
- I am not detecting an advantage of getting a pointer from sha3_Finalize v.s. making a different version of Finalize that will write into a passed-in buffer. One can easily write a wrapper to do this.

**Comment by HarryR** [comment]
Hey, thanks 👍 

I was just trying to provide a review in comparison to many other common hash function implementations (such as in libcrypto, the Linux kernel) and trying to describe the differences between your implementation and the de-facto standard APIs.

I'll put together a pull request for Windows build (along with appveyor CI).

With macros/enums for output size, I guess the rule of thumb is to 'avoid magic or unexplained numbers in source code'.

Re 'Finalize' copying to output buffer, the only reason I can think is that it helps to make the interface more idiot proof. Although tbh I don't think it matters.
